// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoN1gdBd3-cEB-xrI4SVsX7myceOgKjWM',
    appId: '1:148949084952:web:bf63588e03c9b04c6c0c6d',
    messagingSenderId: '148949084952',
    projectId: 'appeducation-ef425',
    authDomain: 'appeducation-ef425.firebaseapp.com',
    storageBucket: 'appeducation-ef425.appspot.com',
    measurementId: 'G-8MKJ8XFPRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOyHJvfWDEfxGjIwfIJo4B7xuyoqWhs40',
    appId: '1:148949084952:android:602a5a29d23a5b606c0c6d',
    messagingSenderId: '148949084952',
    projectId: 'appeducation-ef425',
    storageBucket: 'appeducation-ef425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNXGTDwimsAEXBHen6hZHIAHQ_Psq_520',
    appId: '1:148949084952:ios:cd030203e92486956c0c6d',
    messagingSenderId: '148949084952',
    projectId: 'appeducation-ef425',
    storageBucket: 'appeducation-ef425.appspot.com',
    iosClientId: '148949084952-mp5to3bvjbsposihh1t5smqo8cj61o72.apps.googleusercontent.com',
    iosBundleId: 'com.example.appeducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNXGTDwimsAEXBHen6hZHIAHQ_Psq_520',
    appId: '1:148949084952:ios:cd030203e92486956c0c6d',
    messagingSenderId: '148949084952',
    projectId: 'appeducation-ef425',
    storageBucket: 'appeducation-ef425.appspot.com',
    iosClientId: '148949084952-mp5to3bvjbsposihh1t5smqo8cj61o72.apps.googleusercontent.com',
    iosBundleId: 'com.example.appeducation',
  );
}
